### ISSUE TITLE
Make `key_properties` config optional

### ISSUE THREAD

**Issue by radbrt** [MeltanoLabs/tap-sftp#5]
For various reasons, users might not want, need or be able to specify key columns in their table. In cases without defined key columns, the file name + line number would serve as a key.

Currently, it is not possible to leave out the `key_properties` config, and it is not possible to specify the meta-columns `_sdc_source_file` and `_sdc_source_lineno` as keys, since these do not exist in the CSV file.

@pnadolny13 speculated that mappers might solve this, and while I see that a mapper could replace they `table-key-properties` field of the schema, the table config would still need a `key_properties` field only to be overwritten by such a mapper.

A basic implementation of this (needlessly intertwined with the implementation of column name sanitation) is at https://github.com/radbrt/tap-sftp/tree/sanitize_header.

**Comment by pnadolny13** [comment]
@radbrt the `key_properties` attribute is required in the table config but it doesnt look like its required by the actual [code that syncs the file](https://github.com/MeltanoLabs/tap-sftp/blob/43618f549edf003a405bfba2adb7299655796ff0/tap_sftp/singer_encodings/csv_handler.py#L35). It looks like its just using it to validate that the file has the expected key. I wonder if you put `[]` or null in there if it will work for your case. If that does work then making it an optional table config value would be an easy path forward, allowing users to use mappers if they need a key property field for their target like you do for target-snowflake. In which case you could create a surrogate key by combining multiple values in the record using the mapper.

Would that work?

Also one other thing to consider is that target-snowflake has an option to [not require a primary key field](https://hub.meltano.com/loaders/target-snowflake#primary-key-required), which might solve your problem without any code changes also.

@aaronsteers @edgarrmondragon I was chatting with Henning and weighing whether we think this is generically useful and could be implemented in the tap or if its too custom to the use case. What do you think? I'm trying to find a way to solve it with mappers or the target configs to avoid custom logic in the tap.

**Comment by radbrt** [comment]
@pnadolny13 An empty key field does seem to work, which makes sense. There's lots for me to learn here. The only edge case I can think of is then if some file has been "accidentally" touched, or intentionally appended to, using filename and line numbers as a key would prevent duplicates.

**Comment by radbrt** [comment]
Thinking back on the discussions we've had in our team (we have many different, weird ftp sources), we have seen both cases where we suspect one file has been appended to, as well as cases where the entire file has been replaced with a new one. In the latter case, having real business keys would probably solve the issue, but I there are potentially a lot of bugs that might be features, and vice versa. Just thinking out loud.

**Comment by radbrt** [comment]
I had a meeting with a colleague yesterday to talk this through, and the clearest way to think about the use case is perhaps that the file name is a part of the unique key and contains important business information.

Leaving the key-properties array blank would probably work for us in practice, but relies too heavily on the assumption that old, already loaded files aren't accidentally touched and given an updated timestamp.

I don't know enough about mappers yet but I see that this probably could be done with a mapper that changes they key columns as well. This adds some complexity for users, however.

I suggest we allow metadata columns to be referenced in the key properties field, as this would be a quite generic feature that is also well hidden for users that don't need it, while potentially removing the need for a mapper.

I am less convinced than before about the utility of making the keys field optional - doing so would make setup easier, but the implicit assumption might not align with the assumptions of the user, with unfortunate results. This is perhaps a bigger question about user experience on Meltano in general.

Any thoughts @pnadolny13 @aaronsteers @edgarrmondragon ?

**Comment by pnadolny13** [comment]
@radbrt yeah I'm also not convinced that an optional key-properties field is the way to go.

>we have seen both cases where we suspect one file has been appended to, as well as cases where the entire file has been replaced with a new one.
> ........
>Leaving the key-properties array blank would probably work for us in practice, but relies too heavily on the assumption that old, already loaded files aren't accidentally touched and given an updated timestamp.

My understanding from a quick refresh of this tap is that if the file is replaced or appended to it would be reprocessed using the incremental load feature because the [modified_at timestamp of the file](https://github.com/MeltanoLabs/tap-sftp/blob/43618f549edf003a405bfba2adb7299655796ff0/tap_sftp/client.py#L146) would have changed and no longer matches the bookmarked state.

Usually this would send a duplicate record to the target that would manage deduping using the key property when trying to load to the destination. But in your case you dont have a natural key for the key property so you would either be responsible for assigning an appropriate key using a mapper (only because a natural key doesnt exist) or disabling the target's requirement for a key meaning you'll have duplicate records in your destination and would need to deduplicate in your staging transformation logic.

I agree this is complex for the user to manage so I'm all for a simpler approach.

>Currently, it is not possible to leave out the key_properties config, and it is not possible to specify the meta-columns _sdc_source_file and _sdc_source_lineno as keys, since these do not exist in the CSV file.
> ...
>I suggest we allow metadata columns to be referenced in the key properties field, as this would be a quite generic feature that is also well hidden for users that don't need it, while potentially removing the need for a mapper.

Wouldnt the combination of those 2 metadata fields potentially be unreliable if there's a chance that the file is overwritten? Like the line number might change so the same record ends up with 2 different unique keys.

Again not against your suggested feature but wanted to throw another one out there too - what if we provide a config flag like `generate_unique_key` that generates a unique key for each row for you using a hash of the entire row of data? I would assume thats the most reliable way to know that two records are the same in order to dedup. If the order of the rows change, the data is still the same so the unique key is the same. We could give the user the ability to provide a list of fields we should use to generate a unique key but that could be error prone and potentially tedious to configure. I dont think hashing the row is a huge performance hit so it might provide a simpler, more reliable, approach with minimal performance loss.

@radbrt What do you think about that?

@aaronsteers @edgarrmondragon is my understanding right? Any thoughts on the performance impact of a row hash?

**Comment by radbrt** [comment]
@pnadolny13  We went into production today, with a slightly modified version that allowed reference to the metadata columns in key_properties. I agree the line number trick is risky if someone replaces a file, but I'm all for giving people the option and take their own risks.

We ended up not using line numbers, but the partial business keys + the file name, exactly because it would avoid line numbers.

I really like the row hash idea, does it make sense to open a separate issue for that one?

**Comment by radbrt** [comment]
PR https://github.com/MeltanoLabs/tap-sftp/pull/8 makes it possible to use filename and line number metadata columns in key properties, while keeping the rest the same. Changing focus to documentation instead of adding/changing defaults.

**Comment by pnadolny13** [comment]
>I really like the row hash idea, does it make sense to open a separate issue for that one?

I created https://github.com/MeltanoLabs/tap-sftp/issues/10 to track it outside this issue thread.

>PR https://github.com/MeltanoLabs/tap-sftp/pull/8 makes it possible to use filename and line number metadata columns in key properties, while keeping the rest the same. Changing focus to documentation instead of adding/changing defaults.

@radbrt look great! I approved the PR and we can close this issue once its merged.
